### PR TITLE
Upgrades sonarqube helm charts version and enabling persistence

### PR DESCRIPTION
**Pull request by seansund**
Co-authored-by: Ramya Raghuveera <ramragh1@in.ibm.com>
Signed-off-by: Sean Sundberg <seansund@us.ibm.com>

### CODE REVIEW

**Comment by seansund** [comment]
The `install-plugins` init container is failing with a file permission issue

```
curl: (23) Failure writing output to destination
```

**Review by mjperrins — COMMENTED** [review]
Why remove Python, we have some Machine Learning Models that require this support ?

**Comment by RamyaRaghuveera** [comment]
@mjperrins The latest version of sonarqube has the language plugins inbuilt. Hence, installing plugins explicitly is not needed and gives error: "Web server startup failed: Fail to update plugin: Python Code Quality and Security. Built-in feature with same key already exists: python. Move or delete plugin from extensions/downloads directory"

**Comment by mjperrins** [comment]
OK understand, if we can make sure we do not lose support for the key languages

**Comment by RamyaRaghuveera** [comment]
Sure Matt. This PR upgrades the Sonarqube helm chart to version 9.9.0. Enabling persistence creates file permission issues. Hence, has been disabled

**Pull request closed without merging**
